### ISSUE TITLE
How can I use the translate module in conjunction with ng-datatable

### ISSUE THREAD

**Issue by MichelFigueira** [bhaveshpatel200/ng-datatable#2]
I have a TranslateService to work on the translations part, however, as the table initializes before the constructor, I am unable to call my service to look for the correct translation in json.

I didn't find any field that I can use in the slot to force a new column title, any ideas?
Example: 
               ` <ng-template slot="code" let-value="data" **title="aaaaaaaa"**>`

**Comment by bhaveshpatel200** [comment]
Hi Michel Figueira,

You can add translated title in the column definitions as like as provided in screenshot.
`{ field: 'name', title: this.translate.instant('name'), cellClass: 'font-semibold' },`

![image](https://github.com/bhaveshpatel200/ng-datatable/assets/49618979/557f42e0-4b05-43bd-b71b-3b0c32df387e)
