### ISSUE TITLE
No effect when changing source code

### ISSUE THREAD

**Issue by yagmursezendemir** [bhaveshpatel200/ng-datatable#5]
I'm just using the fesm2020 file. When I change the text, my old version remains. I cleared all cache. What could be the reason?
![fesm2020 1](https://github.com/user-attachments/assets/d1f3606b-dce8-4d11-8ceb-36202d27b692)
![fesm2020 2](https://github.com/user-attachments/assets/b216ab04-3a38-4fcd-9d6e-a674a2db30e7)

**Comment by bhaveshpatel200** [comment]
Why you directly changed like this, if any updates will come and installed packages will be overwrite again with original copy.

**Comment by yagmursezendemir** [comment]
I want to translate it to another language and not use some features. For example, clearing the checkbox when the page changes. How can I do it?

**Comment by bhaveshpatel200** [comment]
then you can forked this package and update your way and use that.

**Comment by yagmursezendemir** [comment]
Then the updates will not affect it and I can change it as I want, right?

**Comment by bhaveshpatel200** [comment]
You need to forked my copy, update your changes, publish on npm package and use that package in your project instead of mine.

**Comment by yagmursezendemir** [comment]
So why did the first situation happen? In the 1-2-3 texts, I made 1 into 2, but I couldn't make 2 into 3. appeared as 2

**Comment by bhaveshpatel200** [comment]
I don't know what you are doing.

**Comment by yagmursezendemir** [comment]
Just like in the first image I shared. It did not change when I changed the source code

**Comment by bhaveshpatel200** [comment]
I don't have an idea and never tried to update files from fesm2020 folder.

**Comment by yagmursezendemir** [comment]
okey thanks
